{-
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
  first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
  even-valued terms.
-}

fibb acc x0 x1
    | x2 > 4000000 = acc
    | mod x2 2 == 0 = fibb (acc + x2) x1 x2
    | otherwise = fibb acc x1 x2
    where x2 = x0 + x1

problem2 = fibb 2 1 2